### ISSUE TITLE
Shouldn't tld_length be 5 instead of 6?

### ISSUE THREAD

**Issue by rstacruz** [fphilipe/xipio#2]
according to: https://gist.github.com/toolmantim/6632690

**Comment by fphilipe** [comment]
example | com
------ | ------
- | 1

example | 123 | 123 | 123 | 123 | xip | io
------ | ------ | ---------- | --------- | -------- | -------- | --------
- | 6 | 5 | 4 | 3 | 2 | 1

**Comment by rstacruz** [comment]
I believe that should be:

| www | google | com |
|---|---|---|
| subdomain | domain | 1 |

(subdomain is `www`)

| example | 127 | 0 | 0 | 1 | xip | io |
|---|---|---|---|---|---|---|
| subdomain | domain | 5 | 4 | 3 | 2 | 1 |

(subdomain is `example`)

**Comment by fphilipe** [comment]
But the setting is called TLD, top level domain, i.e. everything that comes after your domain. This is independent of the subdomain. So `foo.bar.com` has a TLD length of 1, `foo.bar.co.uk` has a TLD length of 2, `foo.bar.127.0.0.1.xip.io` has a TLD length of 6.
